// Seti file-type icons from VS Code's theme-seti, delivered as a WOFF font.
// See LICENSE.txt for attribution. mapping.ts is regenerated by
// scripts/build-seti-mapping.js.

import React from 'react';
import { injectStyle } from '../../inject-style';
import setiWoff from './seti.woff';
import { DEFAULT_ICON, FILE_EXTS, FILE_NAMES, IconSpec } from './mapping';

const FONT_FAMILY = 'seti';

injectStyle(
  'seti-icons',
  `
    @font-face {
      font-family: '${FONT_FAMILY}';
      src: url('${setiWoff}') format('woff');
      font-display: block;
    }
  `,
);

/**
 * Resolves a file path to a Seti icon glyph + color.
 * Tries `fileNames` first (exact basename match), then walks dotted
 * extensions from longest to shortest (e.g. "foo.css.map" → "css.map" → "map"),
 * and finally falls back to the default file glyph.
 */
function iconFor(filePath: string): IconSpec {
  const base = (filePath.split('/').pop() ?? '').toLowerCase();

  const byName = FILE_NAMES[base];
  if (byName) return byName;

  const parts = base.split('.');
  for (let i = 1; i < parts.length; i++) {
    const ext = parts.slice(i).join('.');
    const hit = FILE_EXTS[ext];
    if (hit) return hit;
  }

  return DEFAULT_ICON;
}

interface FileIconProps {
  path: string;
  size?: number;
}

export const FileIcon: React.FC<FileIconProps> = React.memo(({ path, size = 14 }) => {
  const [glyph, color] = iconFor(path);
  return (
    <span
      aria-hidden="true"
      style={{
        width: size,
        flexShrink: 0,
        fontFamily: FONT_FAMILY,
        fontSize: size,
        lineHeight: 1,
        color,
        textAlign: 'center',
      }}
    >
      {glyph}
    </span>
  );
});
